apiVersion: apps/v1
kind: Deployment
metadata:
  name: analyticsapi-deployment
  labels:
    app: analyticsapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analyticsapi
  template:
    metadata:
      labels:
        app: analyticsapi
    spec:
      containers:
        - name: analytics
          image: childhealthbookacr2.azurecr.io/analytics
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "64Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: analyticsapi-service
spec:
  selector:
    app: analyticsapi
  ports:
    - protocol: TCP
      port: 80