apiVersion: apps/v1
kind: Deployment
metadata:
  name: childapi-deployment
  labels:
    app: childapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: childapi
  template:
    metadata:
      labels:
        app: childapi
    spec:
      containers:
        - name: child
          image: childhealthbookacr2.azurecr.io/child
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "64Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: childapi-service
spec:
  selector:
    app: childapi
  ports:
    - protocol: TCP
      port: 80