apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatewayapi-deployment
  labels:
    app: gatewayapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatewayapi
  template:
    metadata:
      labels:
        app: gatewayapi
    spec:
      containers:
        - name: gateway
          image: childhealthbookacr2.azurecr.io/gateway
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "64Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: gatewayapi-service
spec:
  selector:
    app: gatewayapi
  ports:
    - protocol: TCP
      port: 80